### ISSUE TITLE
Libary does not compile

### ISSUE THREAD

**Issue by zettymaster** [adafruit/Adafruit_FeatherOLED#23]
- Arduino board:  Feather M0 Bluefruit (but any board should be fine)

- Arduino IDE version:  1.8.16

- List the steps to reproduce the problem below: 
Try to compile the example sketches

Error (only relevant message): 
/home/zetty/Arduino/libraries/Adafruit_Feather_OLED/Adafruit_FeatherOLED_SH110X.cpp: In member function 'void Adafruit_FeatherOLED_SH110X::init()':
/home/zetty/Arduino/libraries/Adafruit_Feather_OLED/Adafruit_FeatherOLED_SH110X.cpp:118:3: error: 'begin' was not declared in this scope
  118 |   begin(0x3C, true);
      |   ^~~~~

Installed Libraries (again, only the relevant ones listed):

- Adafruit Feather OLED (1.0.5)
- Adafruit SHX110X (2.1.1)
- Adafruit SSD1306
- Adafruit GFX Library (1.10.12)

**Comment by ladyada** [comment]
@Andrewiski hiya can you take a look, probably just needs the object name updated!

**Comment by Andrewiski** [comment]
@Zettymaster With the Error being on begin(0x3c,true) at first glance it would appear you do not have the Wire Library loaded.  

Please ensure you have the following code at the top of your Arduino file.

`
#include <Wire.h>
`

Wire.h is the library that allows IC2 to function and the Feather OLED is an I2C device.

Are you able to share your INO file that is giving the error and I will be able to better assist.

Thanks

Andy

**Comment by caternuson** [comment]
Should that line 118 be?
```cpp
_init(0x3C, true);
```
So it calls the base class method here:
https://github.com/adafruit/Adafruit-GFX-Library/blob/223f914d0e092cc24723182a2e3273e61c4b22ea/Adafruit_GrayOLED.h#L77

I can at least pass a test compile for a Feather M0 target by making that change.

for ref:
```
class Adafruit_FeatherOLED_SH110X : public Adafruit_SH110X
class Adafruit_SH110X : public Adafruit_GrayOLED
class Adafruit_GrayOLED : public Adafruit_GFX
```

**Comment by ladyada** [comment]
fixed in latest commits!
