### ISSUE TITLE
Broken links in README.MD [access denied]

### ISSUE THREAD

**Issue by AKopytenko** [adafruit/Adafruit_FeatherOLED#26]
When I try to follow the links from README.MD
- http://www.adafruit.com/products/2900 (128x32)
- https://www.adafruit.com/product/4650 (128x64)

have an error:
```
Error 1020 Ray ID: 6cd0fc3c9f41453a • 2022-01-13 19:21:02 UTC
Access denied
```
Where can find instructions for working with the library?

**Comment by caternuson** [comment]
Weird. Those links are still valid and working here. How are you trying to access the links?

**Comment by caternuson** [comment]
Could be. This seems like a general issue with internet access from a specific location, so closing since not a library issue.
