### ISSUE TITLE
Adafruit_FeatherOLED::clearMsgArea

### ISSUE THREAD

**Issue by TobbeJ** [adafruit/Adafruit_FeatherOLED#6]
the function Adafruit_FeatherOLED::clearMsgArea should not call display() by itself.
if this is done it will likely cause display to flash.

what is happening for me is something like:
clearMsgArea()
draw stuff.
display();

this results in:
msg area getting cleared.
display();
draw my own stuff
display();

this gives "flashing"

**Comment by makermelissa** [comment]
You can now pass false and it won't update automatically. :)
