### ISSUE TITLE
Here is an update for the battery.ino example - nrf52 Feather support

### ISSUE THREAD

**Issue by iprepiprep** [adafruit/Adafruit_FeatherOLED#8]
Great job guys on the library. Hope you can make use of the following

.........
#elif defined(ARDUINO_FEATHER52)
loat getBatteryVoltage() {
  int raw;

  // Set the analog reference to 3.0V (default = 3.6V)
  analogReference(AR_INTERNAL_3_0);

  // Set the resolution to 12-bit (0..4095)
  analogReadResolution(12); // Can be 8, 10, 12 or 14

  // Let the ADC settle
  delay(1);

  // Get the raw 12-bit, 0..3000mV ADC value
  raw = analogRead(VBAT_PIN);

  // Set the ADC back to the default settings
  analogReference(AR_DEFAULT);
  analogReadResolution(10);

  // Convert the raw value to compensated mv, taking the resistor-
  // divider into account (providing the actual LIPO voltage)
  // ADC range is 0..3000mV and resolution is 12-bit (0..4095),
  // VBAT voltage divider is 2M + 0.806M, which needs to be added back
  return ((float)raw * VBAT_MV_PER_LSB * VBAT_DIVIDER_COMP)/1000.0;
}

**Comment by iprepiprep** [comment]
Updated version
loat getBatteryVoltage() {
  int raw;

  // Set the analog reference to 3.0V (default = 3.6V)
  analogReference(AR_INTERNAL_3_0);

  // Set the resolution to 12-bit (0..4095)
  analogReadResolution(12); // Can be 8, 10, 12 or 14

  // Let the ADC settle
  delay(1);

  // Get the raw 12-bit, 0..3000mV ADC value
  raw = analogRead(VBAT_PIN);

  // Set the ADC back to the default settings
  analogReference(AR_DEFAULT);
  analogReadResolution(10);

  // Convert the raw value to compensated mv, taking the resistor-
  // divider into account (providing the actual LIPO voltage)
  // ADC range is 0..3000mV and resolution is 12-bit (0..4095),
  // VBAT voltage divider is 2M + 0.806M, which needs to be added back
  return ((float)raw * VBAT_MV_PER_LSB * VBAT_DIVIDER_COMP)/1000.0;
}

**Comment by makermelissa** [comment]
Thanks, I had to look up a few defs from another example, but it worked.
